//! Cross-validation: decode FT8 WAVs produced by the *independent* reference
//! encoder (ft8_lib `gen_ft8`) with our from-scratch decoder. If these pass, our
//! sync/demod/LDPC/unpack chain is interoperable with real WSJT-X-format signals,
//! not just self-consistent with our own encoder.
//!
//! Fixtures are 12 kHz / 16-bit / mono / 15 s, generated by:
//!   gen_ft8 "<MESSAGE>" out.wav <AUDIO_FREQ_HZ>

use modes::{Protocol, decode};
use std::path::Path;

/// Minimal canonical-WAV reader (16-bit PCM mono) — no external crates.
fn read_wav_mono(path: &Path) -> (Vec<f32>, u32) {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let sample_rate = u32::from_le_bytes([bytes[24], bytes[25], bytes[26], bytes[27]]);
    // Find the "data" subchunk.
    let mut i = 12;
    let (data_off, data_len) = loop {
        let id = &bytes[i..i + 4];
        let sz =
            u32::from_le_bytes([bytes[i + 4], bytes[i + 5], bytes[i + 6], bytes[i + 7]]) as usize;
        if id == b"data" {
            break (i + 8, sz);
        }
        i += 8 + sz;
    };
    let samples = bytes[data_off..data_off + data_len]
        .chunks_exact(2)
        .map(|c| i16::from_le_bytes([c[0], c[1]]) as f32 / 32768.0)
        .collect();
    (samples, sample_rate)
}

fn fixture(name: &str) -> (Vec<f32>, u32) {
    let p = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    read_wav_mono(&p)
}

const CASES: &[(&str, &str, f32)] = &[
    ("cq_k1abc_1000.wav", "CQ K1ABC FN42", 1000.0),
    ("rpt_w9xyz_1500.wav", "K1ABC W9XYZ -15", 1500.0),
    ("rr73_2000.wav", "W9XYZ K1ABC RR73", 2000.0),
    ("cqdx_vk3abc_800.wav", "CQ DX VK3ABC QF22", 800.0),
];

#[test]
fn decodes_reference_fixtures() {
    for &(file, expect, approx_freq) in CASES {
        let (sig, sr) = fixture(file);
        assert_eq!(sr, 12000, "{file} should be 12 kHz");
        let decodes = decode(&sig, sr, Protocol::Ft8);
        let got = decodes
            .iter()
            .find(|d| d.message == expect)
            .unwrap_or_else(|| {
                panic!(
                    "{file}: expected `{expect}`, got {:?}",
                    decodes.iter().map(|d| &d.message).collect::<Vec<_>>()
                )
            });
        assert!(
            (got.freq_hz - approx_freq).abs() < 7.0,
            "{file}: freq {} Hz vs expected ~{approx_freq} Hz",
            got.freq_hz
        );
    }
}

#[test]
fn decodes_reference_ft4() {
    // FT4 = 4-GFSK, 7.5 s slot, payload whitening — separate path from FT8.
    let (sig, sr) = fixture("ft4_cq_1200.wav");
    let decodes = decode(&sig, sr, Protocol::Ft4);
    let got = decodes
        .iter()
        .find(|d| d.message == "CQ K1ABC FN42")
        .unwrap_or_else(|| {
            panic!(
                "FT4: expected `CQ K1ABC FN42`, got {:?}",
                decodes.iter().map(|d| &d.message).collect::<Vec<_>>()
            )
        });
    assert!(
        (got.freq_hz - 1200.0).abs() < 7.0,
        "FT4 freq {}",
        got.freq_hz
    );
}

#[test]
fn decodes_multiple_overlapping_signals() {
    // Sum two independent reference signals (different audio freqs) into one slot
    // and confirm both decode — the realistic FT8 case of many signals at once.
    let (mut a, sr) = fixture("cq_k1abc_1000.wav");
    let (b, _) = fixture("rr73_2000.wav");
    for (x, y) in a.iter_mut().zip(b.iter()) {
        *x += *y;
    }
    let decodes = decode(&a, sr, Protocol::Ft8);
    let msgs: Vec<&String> = decodes.iter().map(|d| &d.message).collect();
    assert!(msgs.iter().any(|m| *m == "CQ K1ABC FN42"), "got {msgs:?}");
    assert!(
        msgs.iter().any(|m| *m == "W9XYZ K1ABC RR73"),
        "got {msgs:?}"
    );
}
