//! Country-flag icons for the Call Sign panel.
//!
//! Real flag images, keyed by ISO 3166-1 alpha-2 code, embedded into the binary
//! at build time from `assets/flags/<iso>.png` (see `build.rs` and the
//! `ATTRIBUTION.md` there) so they render fully offline. Decoded textures are
//! cached per ISO on first use. Any ISO without a bundled image (or that fails
//! to decode) falls back to a neutral chip showing the code. Phase 1 of
//! `docs/call_sign_lookup_panel.md`.

use std::cell::RefCell;
use std::collections::HashMap;

use eframe::egui;
use egui::{Align2, Color32, CornerRadius, Pos2, Rect, Stroke, TextureHandle, TextureOptions};

use crate::theme::{Palette, mono};

// `FLAGS: &[(&str, &[u8])]` — (lowercase ISO, PNG bytes), generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/flags_data.rs"));

thread_local! {
    // Decoded textures by lowercase ISO. `None` marks "no image / decode failed"
    // so we chip without retrying every frame. The GUI is single-threaded, so a
    // thread-local keeps the handles alive for the app's life without shared state.
    static CACHE: RefCell<HashMap<String, Option<TextureHandle>>> = RefCell::new(HashMap::new());
}

fn flag_png(iso_lower: &str) -> Option<&'static [u8]> {
    FLAGS
        .iter()
        .find(|(k, _)| *k == iso_lower)
        .map(|(_, bytes)| *bytes)
}

fn texture(ctx: &egui::Context, iso_lower: &str) -> Option<TextureHandle> {
    if let Some(cached) = CACHE.with(|c| c.borrow().get(iso_lower).cloned()) {
        return cached;
    }
    let loaded = flag_png(iso_lower).and_then(|bytes| {
        let rgba = image::load_from_memory(bytes).ok()?.to_rgba8();
        let (w, h) = rgba.dimensions();
        let img = egui::ColorImage::from_rgba_unmultiplied([w as usize, h as usize], rgba.as_raw());
        Some(ctx.load_texture(format!("flag_{iso_lower}"), img, TextureOptions::LINEAR))
    });
    CACHE.with(|c| c.borrow_mut().insert(iso_lower.to_string(), loaded.clone()));
    loaded
}

/// Draw the flag for `iso` into `rect` — the image aspect-fit and centered, with
/// a thin frame. Unknown/unbundled codes get a labeled chip so the panel always
/// shows something keyed to the country.
pub fn draw_flag(
    ctx: &egui::Context,
    painter: &egui::Painter,
    rect: Rect,
    iso: &str,
    pal: &Palette,
) {
    let iso_lower = iso.to_ascii_lowercase();
    let Some(tex) = texture(ctx, &iso_lower) else {
        chip(painter, rect, iso, pal);
        return;
    };
    // Fit the flag inside the box without distorting its aspect ratio.
    let [iw, ih] = tex.size();
    let scale = (rect.width() / iw as f32).min(rect.height() / ih as f32);
    let fitted = Rect::from_center_size(rect.center(), egui::vec2(iw as f32 * scale, ih as f32 * scale));
    painter.image(
        tex.id(),
        fitted,
        Rect::from_min_max(Pos2::ZERO, Pos2::new(1.0, 1.0)),
        Color32::WHITE,
    );
    painter.rect_stroke(
        fitted,
        CornerRadius::ZERO,
        Stroke::new(1.0, pal.dim.gamma_multiply(0.8)),
        egui::StrokeKind::Inside,
    );
}

fn chip(painter: &egui::Painter, rect: Rect, iso: &str, pal: &Palette) {
    painter.rect_filled(rect, CornerRadius::ZERO, pal.screen_bg);
    painter.rect_stroke(
        rect,
        CornerRadius::ZERO,
        Stroke::new(1.0, pal.dim.gamma_multiply(0.8)),
        egui::StrokeKind::Inside,
    );
    painter.text(
        rect.center(),
        Align2::CENTER_CENTER,
        iso,
        mono((rect.height() * 0.5).clamp(8.0, 13.0)),
        pal.sub,
    );
}
